### ISSUE TITLE
Client Crashes when attempting to Create Immersive Engineering Multi-block Structures.  (All the Mods 7, MC 1.18.1)

### ISSUE THREAD

**Issue by figori** [KubeJS-Mods/KubeJS-Immersive-Engineering#4]
See previous post from Immersive Engineering.

https://github.com/BluSunrize/ImmersiveEngineering/issues/5180

**Comment by figori** [comment]
Specifically returning Null here:

java.lang.NullPointerException: Cannot read field "scriptManager" because "dev.latvian.mods.kubejs.server.ServerScriptManager.instance" is null

**Comment by MaxNeedsSnacks** [comment]
Forgot to add: AllTheMods/ATM-7#266 will obviously be closed by this
