### ISSUE TITLE
GardenCloche Recipes wont work with IE version 1.18.2-8.0.1-147

### ISSUE THREAD

**Issue by lays24mc** [KubeJS-Mods/KubeJS-Immersive-Engineering#5]
Hi,

as soon as I install the latest IE version, my Garden Cloches scripts don't work anymore. I get the following error message in the server.text: [https://pastebin.com/tRWCwiyL]()

As soon as I change them back to version 1.18.2-8.0.0-146, they work fine again. I have looked once and IE has changed the Recipes Serializer: [https://github.com/BluSunrize/ImmersiveEngineering/commit/265b8b23852a0c2cb43a60e056fdb29e2660b5b6](url)

Possibly this is interesting for you :)

My Cloche Code: [https://pastebin.com/0KbmUB3X](url)

**Comment by MaxNeedsSnacks** [comment]
Should be fixed in https://github.com/KubeJS-Mods/KubeJS/commit/e1484ec390e3f3978a78653adb341d2cd1d92859

**Comment by mosharky** [comment]
KubeJS-added recipes work now, but I can't see the base recipes that IE adds still

**Comment by MaxNeedsSnacks** [comment]
Actually, please track https://github.com/KubeJS-Mods/KubeJS/issues/317 instead, it's apparently still an issue in KubeJS itself
