### ISSUE TITLE
Not Working?

### ISSUE THREAD

**Issue by ZEROX7** [KubeJS-Mods/KubeJS-Immersive-Engineering#7]
hey there i tryed to remove IE recipes by types like:
	event.remove({type: 'immersiveengineeringAlloy'})
	event.remove({type: 'immersiveengineeringBlastFurnace'})
	event.remove({type: 'immersiveengineeringCrusher'})
	event.remove({type: 'immersiveengineeringArcFurnace'})
	event.remove({type: 'immersiveengineeringMetalPress'})
	event.remove({type: 'immersiveengineeringSawmill'})
but the recipes are still loaded

**Comment by MaxNeedsSnacks** [comment]
You'll have to use the actual name of the type, like `immersiveengineering:alloy` or `immersiveengineering:blast_furnace_fuel`
